version: '3'
services:
    server:
        build: 
            dockerfile: Dockerfile.dev
            context: .
        environment:
            - REDISPORT=6379
            - REDISHOST=redis
        volumes:
            - .:/app
        ports:
            - "8080:8080"
    redis:
        image: redis:latest
        volumes:
            - ./data/redis:/data
        ports:
            - 6379:6379